# Site settings
title:       djfoxer - programowanie, IT, Windows, .NET - strona domowa
email:       djfoxer@djfoxer.pl
author:      Grzegorz Jamiołkowski
description: "djfoxer, Grzegorz Jamiołkowski, strona domowa"
baseurl:     ""
url:         "http://blog.djfoxer.pl"
date_format: "%d.%m.%Y"
header_pages:
 - about.md
 - contact.html

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: UA-101030658-1
google_tag_manager:
# Bing services
bing_verification:

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    false
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: false
# Preview image for social media aka og:image and twitter:image
post_preview_image: false

# Facebook Page integration
# (for instant articles and other stuff)
fb_page: false
fb_page_id:

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: djfoxer

# txtpen post comments
# (leave blank to disable txtpen)
txtpen_sitename:

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Social icons
github_username: djfoxer
reddit_username:
bitbucket_username:
stackoverflow_id:
twitter_username: djfoxer
skype_username:
steam_nickname:
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:
telegram_username:
vk_id:

# Post sharing icons
show_sharing_icons: false
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

text:
  pagination:
    newer: 'Nowsze'
    older: 'Starsze'
  share_buttons:
    text:         'Udostępnij post!'
    facebook:     'Udostępnij - Facebook'
    twitter:      'Udostępnij - Twitter'
    googleplus:   'Udostępnij - Google+'
    linkedin:     'Udostępnij - LinkedIn'
    digg:         'Udostępnij - Digg'
    tumblr:       'Udostępnij - Tumblr'
    reddit:       'Udostępnij - Reddit'
    stumbleupon:  'Udostępnij - StumbleUpon'
    hackernews:   'Udostępnij - Hacker News'
  post:
    updated:        'Zaktualizowany'
    minute_read:    'minut(y) czytania'
    related_posts:  'Powiązane posty'
  index:
    coming_soon: 'Startujemy za chwilę...'
  contact:
    email:    'Adres email'
    content:  'Treśc wiadomości'
    subject:  'Jest Nowa wiadomość!'
    submit:   'Wyślij'
    ajax:
      sending:  'wysyłanie..'
      sent:     'Wiadomość wysłana'
      error:    'Błąd :('
  thanks: 'Dzięki za kontakt. Spróbuję odpisać najszybciej jako tylko będę mógł.'
  og_locale: 'pl_PL'

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    :title
paginate:     10
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
